name: Run Pytest

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install . pytest
      shell: bash
    - name: Run tests
      run: pytest -ra
      shell: bash
